version: '2.0'
services:

    web:
        build:
            context: .
            dockerfile: ./Ogma3/Dockerfile
        ports:
        - "5000:5000"
    
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: Dupa@Postgres666
        